### ISSUE TITLE
FEATURE: 'mil' in addition to 'mm'

### ISSUE THREAD

**Issue by herbertp** [apertus-open-source-cinema/alterpcb-tlinesim#1]
It would be great to add 'mil' as alternative unit to 'mm' for dimension input.
Probably the best solution would be to have a toggle button instead of 'mm' which switches (and ideally converts) the unit for each individual input field.

**Comment by BAndiT1983** [comment]
Appears to work, also confirmed by @herbertp. Will close for now, can be re-opened if bugs/problems occur.
